name: main
on:
  push:
    branches:
      - main
permissions:
  contents: read
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.3.2
        with:
          node-version: '16'
          cache: npm
      - run: npm ci
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.3.2
        with:
          node-version: '16'
          cache: npm
      - run: npm ci
      - run: npm run test
  build:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.3.2
        with:
          node-version: '16'
          cache: npm
      - run: npm ci
      - run: npm run build
