type Query {
  user(id: Int!): User
  users: [User!]!
}

type Mutation {
  createUser(username: String!): User
  removeUser(id: Int!): RemoveUserResult
  updateUser(user: UpdateUserInput!): User
}

type User {
  id: Int!
  username: String!
}

type RemoveUserResult {
  success: Boolean!
}

input UpdateUserInput {
  id: Int
  username: String
}
